name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests
      run: npm test
    - name: Generate build
      run: npm run build --if-present
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v1
      with:
          name: react-github-actions-build
          path: dist

  deploy:

    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build

    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
          path: ./dist

      - name: check the files
        run: cd dist
        run: ls
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          publish_dir: ./dist

      # - name: Deploy app to github pages
      #   run: |
      #     git config --global user.name $user_name
      #     git config --global user.email $user_email
      #     git remote set-url origin https://${github_token}@github.com/${repository}
      #     npm run deploy
      #   env:
      #     user_name: 'github-actions[bot]'
      #     user_email: 'github-actions[bot]@users.noreply.github.com'
      #     github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
      #     repository: ${{ github.repository }}

  release:
    runs-on: ubuntu-latest
    # We specify that deploys needs to
    # finish before we create a release
    needs: deploy
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      # Zip the build using external action
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: react-github-actions-release-build.zip
          path: react-github-actions-build
      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-release-build.zip
          path: react-github-actions-release-build.zip
      # Make official GitHub release which will trigger
      # sending the mail with link for access
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: react-github-actions-release-build.zip
          body: https://react-github-actions.s3.amazonaws.com/index.html
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
